### ISSUE TITLE
Snippet pop-down UI notifaction for entering trigger text

### ISSUE THREAD

**Issue by Enkouyami** [atom/snippets#114]
I would like this SublimeText feature added: show a pop-down UI when you've entered a trigger text to let you know you can hit tab to generate the snippet.

**Comment by benogle** [comment]
I think what you want is autocomplete for snippets. This exists already! You can install `autocomplete-plus` then install `autocomplete-snippets`. At some point in the future, these will be installed by default, but not quite yet.
