### ISSUE TITLE
Snippets with same index tab stops exit prematurely

### ISSUE THREAD

**Issue by jordanbtucker** [atom/snippets#118]
This snippet has the same index for its first and last tab stops.

```cson
'.text.html.basic':
  'Spacebars Block':
    'prefix': 'sbblock'
    'body': '''
      {{#${1:block} ${2:context}}}
        ${3:body}
      {{/${1:block}}}'''
```

Tabbing to the the second tab stop works, but tabbing to the third does not. It just inserts a tab as if all tab stops had been reached.

I tracked the cause down to a [recent commit][1517063c]. It seems that the `newSelection` variable is only used when a snippet has more than one tab stop with the same index. However, when this `newSelection` is destroyed (i.e. on the next <kbd>Tab</kbd> press) it destroys the `SnippetExpansion` associated with it. This causes the following <kbd>Tab</kbd> press to [abort its key binding][SL39] because there is no `SnippetExpansion` anymore.

Commenting out [that line][SEL74] fixes this issue, and in my testing it doesn't resurrect the issue that the commit fixed ([atom#4821][ATOM4821]) after following the [reproductions steps][REPO4821].

The funny thing is, you can actually follow those same reproduction steps to reproduce this new issue.

[1517063c]: https://github.com/atom/snippets/commit/1517063c8cd2c8e2be70cdd8dc8a2f94ddf07b2b
[SL39]: https://github.com/atom/snippets/blob/1517063c8cd2c8e2be70cdd8dc8a2f94ddf07b2b/lib/snippets.coffee#L39
[SEL74]: https://github.com/atom/snippets/blob/1517063c8cd2c8e2be70cdd8dc8a2f94ddf07b2b/lib/snippet-expansion.coffee#L74
[ATOM4821]: https://github.com/atom/atom/issues/4821
[REPO4821]: https://github.com/atom/atom/issues/4821#issuecomment-71965142

**Comment by izuzak** [comment]
Adding more :eyes: :tophat: to this and the related PR: https://github.com/atom/snippets/pull/120 -- @as-cii @nathansobo
