### ISSUE TITLE
Backslash in snippet not inserted

### ISSUE THREAD

**Issue by jaenthemaen** [atom/snippets#127]
I'm using a number of latex snippets that have stopped working with the latest update of the editor (running the latest OSX version). The backslash in these snippets is no longer inserted, meaning this:
```coffeescript
'.text.latex':
    '\\emph{}':
        'prefix': 'em'
        'body': '\\emph{$1} $2'
```
leads to this:
```coffeescript
emph{}
```
instead of:
```coffeescript
\emph{}
```
It also doesn't seem to matter where the double backslash is placed in the snippet. It is ignored whenever another letter is following the double backslash.

**Comment by 50Wliu** [comment]
Looks like this broke with #123.  Perhaps try one or three backslashes?

**Comment by jaenthemaen** [comment]
Just did and neither of which is working for me, unfortunately.

**Comment by thomasjo** [comment]
I can confirm that this is broken. Unsure whether this can be reasonably fixed at the snippet level.

**Comment by thomasjo** [comment]
OK, so double-escaping seems to work. Using @jaenthemaen example, this works as expected

```coffee
'.text.tex.latex':
  '\\emph{}':
    'prefix': 'em'
    'body': '\\\\emph{$1} $2'
```

---
**NB:** I changed the grammar scope since this is the scope that `language-latex` uses.

**Comment by izuzak** [comment]
Using 4 backslashes does it for me. Try:

```
'.text.latex':
    '\\emph{}':
        'prefix': 'em'
        'body': '\\\\emph{$1} $2'
```

**Comment by jaenthemaen** [comment]
Indeed, that does the trick! :+1: Thank you!
