### ISSUE TITLE
2 calls to deprecated methods

### ISSUE THREAD

**Issue by INGCRENGIFO** [atom/snippets#131]
I get the following error after installing the bootstrap snippet.

atom-bootstrap3 (2 deprecations)
Store package settings files in the settings/ directory instead of scoped-properties/
Called 1 time
Package.loadSettings - C:\Users\CRISTIAN\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:566:9
<unknown> - C:\Users\CRISTIAN\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:168:43
Package.measure - C:\Users\CRISTIAN\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:147:15
Package.load - C:\Users\CRISTIAN\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:161:12
Use activationCommands instead of activationEvents in your package.json Commands should be grouped by selector as follows:

  "activationCommands": {
    "atom-workspace": ["foo:bar", "foo:baz"],
    "atom-text-editor": ["foo:quux"]
  }
Called 1 time
Package.getActivationCommands - C:\Users\CRISTIAN\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:790:9
Package.hasActivationCommands - C:\Users\CRISTIAN\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:715:20
<unknown> - C:\Users\CRISTIAN\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:169:24
Package.measure - C:\Users\CRISTIAN\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:147:15

**Comment by thomasjo** [comment]
You need to re-open this on the [`atom-bootstrap3` repo](https://github.com/webBoxio/atom-bootstrap3), since that's where the offending code comes from.
