### ISSUE TITLE
overriding scope for snippets installed through packages

### ISSUE THREAD

**Issue by funsterisdafunniest** [atom/snippets#134]
hi, is there any chance to add the functionality of adding a syntax to override scope from snippets that is contained in packages?

i.e. i've installed <a href="https://github.com/webBoxio/atom-bootstrap3">atom-bootstrap3</a> package and i've noticed that the owner of the package only includes html as it's scope. This is problematic since people would usually use other language for templating (php, ruby, ftl, etc)

for now, i resort to manually editing the cson inside the snippets package. I was wondering if there's some code that i can put in my user's snippets.cson to be able to override the scope so that i can use the  snippets for all of my project, which is varying in programming language.

**Comment by izuzak** [comment]
@funsterisdafunniest I think that's not possible currently, but it's a neat idea. For now, you could copy all those snippets to your snippets.cson file and then tweak them as you like. Not the most elegant solution, but it should get the job done.

**Comment by funsterisdafunniest** [comment]
@izuzak thanks! that's probably what i'll do right now. but for future release, can we have some kind of a named container in each packages' snippets cson so that they can be referenced in user's own private snippets.cson? just for preparation, should the override function did got implemented later.

**Comment by benogle** [comment]
Can you make a pr on the repo to add the scopes you want? That seems like
the simplest long term solution here.

**Comment by funsterisdafunniest** [comment]
sure thing! which file should i add or edit? i'm not sure since i never participated in a coffee projects before

**Comment by benogle** [comment]
The scopes are the top level keys in the object defining the snippets. e.g. [this line](https://github.com/webBoxio/atom-bootstrap3/blob/master/snippets/components.cson#L1). Anywhere he has `.text.html`, you could change it. 

However, `.text.html` is part of the root level scopes in PHP (`.text.html.php`) and erb (`.text.html.erb`), so his snippets should work in php, erb, etc. Which language is not working for you? Can you use `cmd-option-p` to display the scopes at your cursor, then paste in a screenshot?

**Comment by funsterisdafunniest** [comment]
@benogle i'm terribly sorry, it seems that the last time i tested it, i didn't turn on autocomplete-snippets. since i didn't see it in my autocomplete, i think it can't be used in atom.

so, should i close this issue or leave it for enhancement? since @izuzak has already marked this as enhancement

**Comment by benogle** [comment]
We can close it. Thanks for letting us know.
