### ISSUE TITLE
Tab stops at the start of an indented line select all leading whitespace

### ISSUE THREAD

**Issue by nathanbuchar** [atom/snippets#140]
This is a pretty specific bug, hopefully I explain it well! 

If you have a snippet with a tab stop that starts at the beginning of a line, it will also select all space to the left of the tab stop. Therefore, if you're attempting to place the snippet within an indented area, the tab stop will also select all the empty space to the left.

_However, this appears to only happen when the snippet is preceded by a multi-line comment._

Below, you'll see two identical snippets, however the first one has a preceding multi-line comment. When tabbing to the `class_name` tab stop, you'll see that it selects too much space, but this is not the case for the second example (the built-in `proto` snippet).

It should be noted that the multi-line comment must be defined as part of the snippet. Writing a multi-line comment, then invoking the `proto` snippet will not cause this bug to occur.

![screen shot 2015-05-20 at 10 40 37 am](https://cloud.githubusercontent.com/assets/1815367/7732616/03823cc0-fede-11e4-9533-3a13968caa39.png)

![screen shot 2015-05-20 at 10 41 45 am](https://cloud.githubusercontent.com/assets/1815367/7732617/0382ea3a-fede-11e4-8b9e-96cd4dc2d410.png)

My snippet definition:

``` cson
'.source.js'
  'Prototypal method':
    'prefix': 'method'
    'body': """
      /**
       * @method ${1:method_name}
       * @description ${2:description}
       */
      ${3:class_name}.prototype.${1:method_name} = function (${4:first_argument}) {
        ${5:// body...}
      };
    """
```

Here, `${3:class_name}` follows a multi-line comment, and also is also at the start of a line.

**Comment by 50Wliu** [comment]
I believe I've seen this while writing my own snippets as well using something like
```
switch(${1:something})
{
    case ${2:somethingElse}
    {
        ${3:/* code */}
    }
   ${4:/* Add more cases through the case snippet */}
}
```

**Comment by nathanbuchar** [comment]
#149 is exhibiting similar behavior, but in that case it's important to note that the tab stop is preceded by a multi-line comment made from `//` instead of `/** */`.

**Comment by caleb531** [comment]
I can confirm that the issue also occurs for me when the snippet is indented. Here's the snippet I used:

```cson
'.source.python':
  'if':
    'prefix': 'if'
    'body': "if ${1:condition}:\n\t${2:pass}\n$3"
```

![bug](https://cloud.githubusercontent.com/assets/872474/8560654/ebecf778-24ce-11e5-9452-67c48fd52b0e.png)

Strangely enough, when the tab stop is preceded by a newline *and a tab* (`\n\t`), then the preceding whitespace is *not* selected:

```cson
'.source.python':
  'if':
    'prefix': 'if'
    'body': "if ${1:condition}:\n\t${2:pass}\n\t$3"
```

![weird-case](https://cloud.githubusercontent.com/assets/872474/8560658/1107cfb0-24cf-11e5-956f-cd7f57e3785c.png)

**Comment by pezioz** [comment]
I have the same behavior.

Is there a plan to correct it?

**Comment by keathley** [comment]
I'm also having this issue. The snippet should produce:

```elixir
  @moduledoc """
  documentation
  """
```

But as others have noted it selects all of the proceeding whitespace:

![atom_example](https://cloud.githubusercontent.com/assets/1642095/14588478/b07650e0-0498-11e6-90d7-0e6ab664fff3.gif)

The snippet definition:

```coffeescript
  'moduledoc':
    'prefix': 'moduledoc'
    'body': """
      @moduledoc \"\"\"
      ${0:documentation}
      \"\"\"
    """
```

The workaround that I've been using is to just change the snippet to:

```coffeescript
  'moduledoc':
    'prefix': 'moduledoc'
    'body': """
      @moduledoc \"\"\"$0
      \"\"\"
    """
```

This requires the user to insert a new line themselves after the snippet is expanded. It works, but it would be nice to figure out a real solution to this. I'm happy to do research or provide other information if it helps.

**Comment by nathanbuchar** [comment]
Woohoo! Thanks @50Wliu :)
