### ISSUE TITLE
def snippet and names with underscore

### ISSUE THREAD

**Issue by ehajri** [atom/snippets#145]
Hello,

How do I fix the `def` snippet so that names with underscores won't mess with next tabbing?

Reproduce:
try, for example, `def` with a name `under_score`.

Regards,

**Comment by lee-dohm** [comment]
I'm not sure what you're seeing. Here is what I tried using Atom v0.205.0-6552d2c on Mac OS X 10.10.3:

1. Open Atom
1. Open a Ruby file (this is assuming that the `def` snippet you're referring to is from Ruby)
1. Go to the end of the file
1. Type `def` and press <kbd>Tab</kbd>
1. Type `under_score` and press <kbd>Tab</kbd>

**Expected and Actual:** Cursor ends up at the end of the line between the line starting with `def` and the line starting with `end`

Can you be more explicit about what exactly you're doing, what you expected to see and what you actually saw?

**Comment by ehajri** [comment]
I've tried with 3 other environments and couldn't reproduce. It seems to be just this machine which is, sadly, the primary one for work.

Language: Python (only)

1. `def`<kbd>Tab</kbd> gives:
>def fname(arg):
>&nbsp;&nbsp;&nbsp;&nbsp;pass

2. Editing the `fname` to `under_score` (i.e. `def under_score`<kbd>Tab</kbd>`(arg):`) gives:

>def under_score(arg)(arg):
>&nbsp;&nbsp;&nbsp;&nbsp;pass

And the first `arg` is highlighted.
3. A third <kbd>Tab</kbd>, will shift the focus to the 2nd `arg` to be highlighted.
4. Forth <kbd>Tab</kbd>, onward, will cause the entire line to be indented with as many tabs.
For example, stopping at 5 tabs will cause something like:
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;def under_score(arg)(arg):
>&nbsp;&nbsp;&nbsp;&nbsp;pass

**Comment by lee-dohm** [comment]
Could you give the following information for the environment where you *can* reproduce the issue?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by ehajri** [comment]
Hi,
* 0.204.0
* Mac OS X Yosemite, 10.10.3
* No. It works as intended.

It appears this issue can be reproduced after installing `autocomplete-plus-python-jedi`.

Disabling it fixes the issue but the thing is, it is helpful as well.

**Comment by lee-dohm** [comment]
Do you have the `autocomplete-snippets` package installed?

**Comment by ehajri** [comment]
Yes, 1.6.3.

**Comment by ehajri** [comment]
Can someone confirm whether this is caused by snippets or autocomplete-plus-python-jedi?

**Comment by lee-dohm** [comment]
It is not caused by snippets. I just ran the snippet on my installation, in a Python file, and it worked fine. I do not have autocomplete-plus-python-jedi installed.

**Comment by omrihar** [comment]
I have the same problem on Arch Linux. The snippet works as described by ehajri when autocomplete-plus-python-jedi is enabled, and it works as expected when the package is disabled.

**Comment by 50Wliu** [comment]
Thanks @omrihar!  In that case, @ehajri, can you please open the issue on autocomplete-plus-python-jedi instead?  Thanks.

**Comment by ehajri** [comment]
For future reference, here is [issue #29](https://github.com/tinloaf/autocomplete-plus-python-jedi/issues/26). Still waiting for a fix.
