### ISSUE TITLE
Adding the current file's file name

### ISSUE THREAD

**Issue by Splike** [atom/snippets#148]
I've tried looking for a command to add the current file's file name to a snippet, but I haven't found anything.

I've added the snippet:

``` cson
'.source.cpp':
  '#include ""':
    'prefix': 'inc'
    'body': '#include "${1:filename}.hpp"'
```

This snippet adds the line:

``` c++
#include "filename.hpp"
```

Instead of the word being "filename", I would like to add the actual filename (without file extension) of the file that the snippet is inserted into.
Is this currently possible? If not, I would like to request this.

**Comment by steveoh** [comment]
I think this would be very cool. I have some snippets that would benefit from this.

**Comment by stryju** [comment]
this would rock

**Comment by juliardi** [comment]
not only current filename, but also current filepath from project root would be great, especially for PHP namespace

**Comment by xixixao** [comment]
Regex on the file path preferably (so you could choose which portion you want to use).

**Comment by mende** [comment]
This would be great!

**Comment by robballou** [comment]
See also #46

**Comment by niklasp** [comment]
+1

**Comment by kafoso** [comment]
+1

**Comment by ccaroon** [comment]
- [x]

**Comment by danikenan** [comment]
+1

**Comment by VasilyShelkov** [comment]
+1

**Comment by MaxGiting** [comment]
+1

**Comment by haasDev** [comment]
+1

**Comment by primalmotion** [comment]
+1

**Comment by dimlock** [comment]
👍

**Comment by jonwu** [comment]
+1

**Comment by davidsf** [comment]
+1

**Comment by huarse** [comment]
+1

**Comment by tothpeter** [comment]
+1

**Comment by jonaskuiler** [comment]
+1

**Comment by rhoglund** [comment]
+1

**Comment by 88mpg** [comment]
+1

**Comment by michaelkrnac** [comment]
+1

**Comment by morustechnology** [comment]
+1

**Comment by drmercer** [comment]
+1

**Comment by brysem** [comment]
+1

**Comment by Floriferous** [comment]
+1

**Comment by thomasjo** [comment]
The +1 comments serve no purpose other than annoying maintainers, and other people who are watching this issue. Therefore I'm locking this issue for the time being.

**Comment by savetheclocktower** [comment]
Several issues are open asking for variable support; I’m anointing #41 as the canonical feature request and closing the others as dupes.
