### ISSUE TITLE
Preceding whitespace selected when tabbing to tab stop after newline

### ISSUE THREAD

**Issue by caleb531** [atom/snippets#157]
Hi,

I've noticed a strange behavior when using Atom snippets for a particular case. It's difficult to describe in words, yet it's quite easy to show visually (which is why I brought screenshots with me). For what it's worth, I am using Atom 1.0.0 on OS X Yosemite (10.10.4).

The following issue applies to any snippet in which a tab stop *immediately* follows a newline character (`\n`). It also seems that the issue *only* occurs if I am already indented when I begin typing the snippet. Here is the snippet used in the below screenshots:

```cson
'.source.python':
  'if':
    'prefix': 'if'
    'body': "if ${1:condition}:\n\t${2:pass}\n$3"
```

And here's a step-by-step expansion/tabbing of that snippet:

1\. Getting ready to expand...

![snippet-0](https://cloud.githubusercontent.com/assets/872474/8559022/96815a06-24bd-11e5-93e1-03c4409cb61a.png)

2\. Looking good...

![snippet-1](https://cloud.githubusercontent.com/assets/872474/8559033/a6c1e926-24bd-11e5-9405-b90704bb33cf.png)

3\. Almost there...

![snippet-2](https://cloud.githubusercontent.com/assets/872474/8559040/ae2dcf0e-24bd-11e5-97ca-af584618f049.png)

4\. And... wait, what?

![snippet-3](https://cloud.githubusercontent.com/assets/872474/8559046/bd876636-24bd-11e5-9efe-88afbd75d262.png)

As you can imagine, I would expect the cursor to be placed at the same column as the initial `if`, yet the cursor somehow starts at the first column and the selection continues up to that same column.

Also, it seems that issue #140 is referencing the same quirky behavior, though considering that the issue is labeled * needs-reproduction*, perhaps my example here can serve as a simple example for testing this behavior.

Thanks very much in advance,
Caleb

**Comment by 50Wliu** [comment]
Hey there @caleb531, this issue and #140 do seem like one and the same, so I'm going to close this in order to keep discussion unified.  I'll also go and remove the `needs-reproduction` label now that someone else has reproduced it :smile:.
