### ISSUE TITLE
Limit to Snippet Variables?

### ISSUE THREAD

**Issue by mnquintana** [atom/snippets#158]
_From @shadowlightwolf89 on July 5, 2015 22:46_

Is there a limit to how many variables can be in a single snippet, and if so, what is that limit? I tried to create a boilerplate snippet that had 9 variables, and it only worked for the first 6 of them. But I'm not sure if that was simply due to a mistype or not...

_Copied from original issue: atom/atom#7723_

**Comment by mnquintana** [comment]
_From @50Wliu on July 6, 2015 1:45_

Hi @shadowlightwolf89, can you please move this over to [atom/snippets](https://github.com/atom/snippets) and then share the snippet in question?  Thanks.
(Also, once you've moved the issue, feel free to close this one.)

EDIT: After some quick investigation, it doesn't seem like there's a limit since the pegjs file uses a `[0-9]+` regex.

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/snippets/issues/158#issuecomment-119546526. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
