### ISSUE TITLE
Docs: link to "native" snippets

### ISSUE THREAD

**Issue by peteruithoven** [atom/snippets#159]
I wanted to create a snippet containing a small tweak to the regular native `html` snippet. It took me quite a while to figure out that they where included in the html language package: 
https://github.com/atom/language-html/blob/master/snippets/language-html.cson
Maybe a link could be added to the readme? This would also automatically add loads of examples.

**Comment by lee-dohm** [comment]
There is mention of the language-html package already in the official documentation:

> Many of the packages come bundled with their own snippets that are specific to that mode. For example, the language-html package that provides support for HTML syntax highlighting and grammar comes with dozens of snippets to create many of the various HTML tags you might want to use.

https://atom.io/docs/v1.0.0/using-atom-snippets

Perhaps just adding a link to the README to the official documentation would be even better?

**Comment by peteruithoven** [comment]
Certainly a good idea! But then I'd like to see a link to that actual file, or a link to the language html package. Not sure how to contribute to those docs though?

**Comment by izuzak** [comment]
> Not sure how to contribute to those docs though?

@peteruithoven The repository for the docs is here: https://github.com/atom/docs

**Comment by peteruithoven** [comment]
Thanks @izuzak !

**Comment by savetheclocktower** [comment]
Since the ensuing PR got merged, I think this is safe to close. #277 and its corresponding PR in settings-view will help make package-provided snippets even more discoverable in Atom 1.33.
