### ISSUE TITLE
Tab stops with selections don't select correct text when curly braces `{}` are present within the desired selection

### ISSUE THREAD

**Issue by stephantabor** [atom/snippets#162]
creating tab stops with selections when there are curly braces in the tab stop selection area doesn't work as desired.

Example:

```JSON
{
  ".source.js": {
    "test": {
      "prefix": "ayy",
      "body": "${1:{ lmao: 0 }}"
    }
  }
}
```

<img width="217" alt="screenshot 2015-07-18 20 16 59" src="https://cloud.githubusercontent.com/assets/8570366/8764050/8965e802-2d8a-11e5-90d4-15c5899aaab2.png">

<img width="143" alt="screenshot 2015-07-18 20 17 07" src="https://cloud.githubusercontent.com/assets/8570366/8764053/93154ac8-2d8a-11e5-8f51-f607c8896717.png">

I tried with JSON and CSON. Also tried escaping various braces in CSON.

**Comment by stephantabor** [comment]
ooh nevermind i figured it out 

```cson
'.source.js':
  'test':
    'prefix': 'ayy'
    'body': '${1:{ lmao: 0 \\}}'
```

**Comment by terrycloth** [comment]
It'd be great if there was something about this in the README. I dunno, maybe this is because I don't write a lot of CoffeeScript, but I wouldn't have ever guessed that you need to escape the backslash instead of escaping the curly bracket itself.

**Comment by terrycloth** [comment]
Just sent a pull request. Figured it'd be easier to write it myself, but you can reject it and write your own explanation, if you prefer.
