### ISSUE TITLE
'}' impossible to preselect in snippet

### ISSUE THREAD

**Issue by palango** [atom/snippets#163]
Hey,

I'm trying to create a snippet that creates the text `"{:?}"`, with the inner part selected. However since the `}` also closes the selection part the last brace always gets lost.

The complete code I use is `println!("${1:{${2::?}}}", ${3});`

There should probably be a counter for opening and closing braces.

**Comment by 50Wliu** [comment]
Please try `\\}` instead.  That escapes the bracket.
