### ISSUE TITLE
Nested snippet selections

### ISSUE THREAD

**Issue by montegoulding** [atom/snippets#168]
I want to be able to create a snippet like this and have it handle deletion of 1:
`'something ${1:hello${2:world}!} ${3:something}'`

At the moment if I delete 1 it won't tab to 3 but if I delete 2 it still tabs to 3 fine. Any chance this is possible?

**Comment by savetheclocktower** [comment]
I can’t reproduce this — I can delete all of `$1`’s content and then jump to `$3` when I hit <kbd>Tab</kbd> — so this appears to be fixed.
