### ISSUE TITLE
Plugin only work for Js files

### ISSUE THREAD

**Issue by danielchikaka** [atom/snippets#169]
I have this strange issue, the plugin seems to work inside only js files. Anyone experiencing the same problem?  How to fix this?

**Comment by CubixSystem** [comment]
+1 In ```jade``` files plugin not work, I expand snippets with 'Enter'

**Comment by lee-dohm** [comment]
Can either of you give more information on how to reproduce your issue? We've had no other reports of snippets not working in files of any particular type. Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Do you have [Emmet](https://atom.io/packages/emmet) installed?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by CubixSystem** [comment]
@lee-dohm thanks for help and useful information, in my case its ```Emmet``` problem

**Comment by lee-dohm** [comment]
@danielchikaka do you have any information on this?

**Comment by damieng** [comment]
No response, closing.
