### ISSUE TITLE
When i create snippets in  .source.gfm（Markdown file）,Appear some notice!

### ISSUE THREAD

**Issue by leebivip** [atom/snippets#189]
windows 10 OS
![image](https://cloud.githubusercontent.com/assets/15789711/12543121/09927712-c367-11e5-93f1-7e87efca14ec.png)

NOTICE

```
Failed to load snippets from 'C:\Users\Li Bei.atom\snippets.cson'
C:\Users\Li Bei\.atom\snippets.cson: unexpected :
```

My snippets:

```
'.source.gfm':
  'title2':
    'prefix': 'bt2'
    'body': '## $1 '
```

Why ?Thanks!!

**Comment by lee-dohm** [comment]
Is this the entire contents of your `snippets.cson` file? Because I don't get the same notice using Atom v1.6.0-dev-62c1f6a on Mac OS X 10.11.2.

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/snippets/issues/189#issuecomment-174661334. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
