### ISSUE TITLE
Set prefix to 'constructor' breaks snippets

### ISSUE THREAD

**Issue by unclejustin** [atom/snippets#191]
The following will break all of your snippets for that source:

``` cson
'.source.ts':
  'console.log':
    'prefix': 'log'
    'body': 'console.log(${1});'
  'class constructor':
    'prefix': 'constructor'
    'body': 'constructor() {${1}}'
```

But changing to the following will fix it:

``` cson
'.source.ts':
  'console.log':
    'prefix': 'log'
    'body': 'console.log(${1});'
  'class constructor':
    'prefix': 'con'
    'body': 'constructor() {${1}}'
```

**Comment by amytruong** [comment]
Hi! I'm having a little trouble reproducing this. Your first snippet works correctly for me.
Can you tell me what OS and version of Atom you're on?

**Comment by unclejustin** [comment]
OSX 10.11.3
Atom 1.4.3

I don't have my laptop with me at the moment. I'll try it again tomorrow and pull a list of plugins too if that helps.

**Comment by 50Wliu** [comment]
Cannot reproduce; no response.
