### ISSUE TITLE
Snippet fails to be able to be parsed: unexpected quotation marks/newline

### ISSUE THREAD

**Issue by bigyihsuan** [atom/snippets#204]
I'm getting this error:
`Failed to load snippets from 'C:\Users\[user].atom\snippets.cson'
C:\Users\[user]\.atom\snippets.cson: unexpected ''`

and I'm using this code:
[Pastebin Link](http://pastebin.com/ZKFZ2bpW)
I've just tried to remove the excess single quotes in the "'prefix': 'data:'''", and now Atom is giving me an unexpected newline error. Changing the number of hard tabs in the triple-quoted code blocks changes nothing with the new line error:
`Failed to load snippets from 'C:\Users\[user].atom\snippets.cson'
C:\Users\[user]\.atom\snippets.cson: unexpected newline`

**Comment by lee-dohm** [comment]
On line 30 you have a comma after `technology` instead of a colon.
