### ISSUE TITLE
Snippets do not work for linux hidden files

### ISSUE THREAD

**Issue by rushl** [atom/snippets#211]
When a filename begins with a dot, snippets do not work. Renaming the file without the dot will enable snippets again.

**Comment by 50Wliu** [comment]
Does this happen in safe mode (`atom --safe`)?  And what Atom version are you using?

**Comment by rushl** [comment]
Yes, it does happen in safe mode. I'm on Atom 1.9.8, but it's done this in previous versions as well.

**Comment by gregrickaby** [comment]
Confirmed. On my local, I like to offload the contents of `wp-content/uploads` to our development server with the following `.htaccess` snippet:

```
# Offload local images to dev environment.
RedirectMatch 301 ^/wp-content/uploads/(.*) http://someclient.devserver.com/wp-content/uploads/$1
```

If I open `snippets.cson` and add the following:

```json
'.source.':

	# Offload /uploads directory to server.
	'Offload /uploads directory to server':
		'prefix': 'offload'
		'body': '''
				# Offload local images to dev environment.
				RedirectMatch 301 ^/wp-content/uploads/(.*) http://{$1}.{$2}.com/wp-content/uploads/$1
				'''
```

However when I open `.htaccess` and try to access this snippet, nothing happens.

Atom 1.11.2

**Comment by ncksnydr** [comment]
@rushl @gregrickaby Came across this post and found a solution. Adding here just incase you—or others like me—still need it.

```
".text.plain":
  'Large Flag':
    'prefix': 'lflag'
    'body': """
    #
    #      ${1:Comment}
    #-------------------------------------------------- #
    """
```

**Comment by savetheclocktower** [comment]
Sounds like this was a matter of scope matching. Closing!
