### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by soat6nn** [atom/snippets#212]
Desktop messneger shows only white screen! dev tools shows that the problem is : Uncaught SyntaxError: Unexpected token ILLEGAL 
![image](https://cloud.githubusercontent.com/assets/21199872/17896614/f23acd64-6959-11e6-98fd-26eebb651d36.png)

![image](https://cloud.githubusercontent.com/assets/21199872/17896644/1724c09e-695a-11e6-96c7-a78f01e4798b.png)

**Comment by 50Wliu** [comment]
Not related to Atom.
