### ISSUE TITLE
cannot enable this plugin

### ISSUE THREAD

**Issue by multivoltage** [atom/snippets#218]
I disabled this plugin because simple touch of tab key give me only one space intead a default tab like other editors.  Now tab key not work, No space is produced.  When I go to setting -> installed and search for this plugin i cannot enable again.

**Comment by 50Wliu** [comment]
If you are still experiencing this issue, please fill out the [issue template](https://raw.githubusercontent.com/atom/snippets/master/ISSUE_TEMPLATE.md).  Thanks.
