### ISSUE TITLE
Variables substitution like SublimeText

### ISSUE THREAD

**Issue by matheo** [atom/snippets#220]
I was looking for an automagical transformation of variables and I found it on SublimeText snippets docs:

```
${var_name/regex/format_string/options}
```

http://docs.sublimetext.info/en/latest/extensibility/snippets.html#substitutions

Is there any possibility to have something like that in Atom?

```
    Original: ${1:Hey, Joe!}
Transformation: ${1/./=/g}

# Output:

      Original: Hey, Joe!
Transformation: =========
```

**Comment by guerrero** [comment]
This issue seems to be a duplication of #40

**Comment by matheo** [comment]
Yep, it seems there's little hope to have this soon :(
