### ISSUE TITLE
Code selections cannot end with '\'

### ISSUE THREAD

**Issue by SelectiveAlso** [atom/snippets#225]
Working in the '.php' scope. Have not tested in other scopes.

Here i have a snippet:
```
'Factory User':
  'prefix': 'fac_user'
  'body': '$user = factory(${1:App\\}User)->create($2);'
```

When expanding this snippet, i get: 
```
$user = factory(${1:App}User)->create();
```

If i put a single '\\' in the snippet like so: 
```
'Factory User':
  'prefix': 'fac_user'
  'body': '$user = factory(${1:App\}User)->create($2);'
```
i get: 
```
$user = factory(AppUser)->create();
```
with 'App' being highlighted.

I think in the first situation, 'App\' should be highlighted, but instead the syntax for the code selection is literally put in the snippet.

**Comment by 50Wliu** [comment]
If you want an actual backslash you would need to quadruple-escape it: `\\\\`.
