### ISSUE TITLE
Feature Request / Maybe I should fork this...

### ISSUE THREAD

**Issue by Code-Ergo-Sum** [atom/snippets#238]
I am writing a snippets package for an API called "APEX API". 
Every function that's called in this API is prefixed by a namespace followed by a period. For example....

apex_collection.add_member

The issue I'm having is that when the user types the "period", the snippet textbox disappears. We need the snippet textbox to remain because there are many functions that are inaccessible because dozens of functions are all under the same namespace (e.g. apex_collection), and since atom only shows you the top 10, there is no way to see the function that the user wants. If, on the other hand, after typing the period, the user were able to continue to see his options, eventually as he types he'd see the function he wants to use.

Why did the Atom team decide to disappear the box after the period button is pressed. Can we change this behavior? Or is there any way that I can take matters into my own hand and code around this behavior?

**Comment by 50Wliu** [comment]
I think there should already be a way to do this - for example, take a look at how [autocomplete-atom-api](https://github.com/atom/autocomplete-atom-api) handles displaying completions for different Atom sub-sections.

**Comment by Code-Ergo-Sum** [comment]
Interesting. I checked it out, but I can't for the life of me determine how they did it. Tips?

**Comment by 50Wliu** [comment]
Looks like most of the work is done in https://github.com/atom/autocomplete-atom-api/blob/260e5acb8b3d65607ae92cc494e3adb88e5c7ca7/lib/provider.coffee#L60.  The completions come from https://github.com/atom/autocomplete-atom-api/blob/260e5acb8b3d65607ae92cc494e3adb88e5c7ca7/completions.json.

**Comment by savetheclocktower** [comment]
Closing because it's not a feature request for this package.
