### ISSUE TITLE
how to deal with \ 

### ISSUE THREAD

**Issue by kudou** [atom/snippets#251]
My configuaration in the snippets 
```coffee
'*':
  'test ':
    'prefix': 'test'
    'body': "echo $1| sed -n '/^[0-9]\+$/p'"
```
when i use  test in any file
it comes out 
`echo $1| sed -n '/^[0-9]+$/p'`
the \ is missing.

atom -v
Atom    : 1.19.6
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by 50Wliu** [comment]
Use `\\\\`
