### ISSUE TITLE
snippet with prefixes of angle brackets and/or hyphens do not expand

### ISSUE THREAD

**Issue by jm3** [atom/snippets#254]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

snippets with prefixes like `>>` or `--` (or `->`, etc.) do not expand.

### Steps to Reproduce

1. create a snippet like so:
```cson
'.source.gfm, .text.plain, .text.html.basic':
  'test (arrows)':
    'prefix': 'xx'
    'body': '→ ←'
```
2. Type "xx" in a plain text or markdown file, and snippet correctly expands to `→ ← `
3. Now change the snippet's prefix from `xx` to `>>`

**Expected behavior:** snippet should expand, as before

**Actual behavior:** nothing happens, snippet is not suggested and does not expand.

**Reproduces how often:** 100%

### Versions

```
% uname -a
Darwin mac 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

% atom --version
Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

% apm --version
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.5
```

### Additional Information

Tested in both plain text and in Markdown.

**Comment by savetheclocktower** [comment]
Can’t reproduce this in plain text or markdown, so I think this has been fixed. Please re-open if this is still occurring for you and we can figure out what else separates your environment from mine.
