### ISSUE TITLE
spiner with help does not work

### ISSUE THREAD

**Issue by guillebalmacedaonline** [atom/snippets#255]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

On write inn class="" not show spiner with Autocompletion for Glyphicons, Fontawesome and Octicons. Also not spiner for label-. Please help.

**Expected behavior:** snippet should expand, as before with help

**Actual behavior:** Actual behavior: nothing happens, snippet is not suggested and does not expand.

Reproduces how often: 100%

### Versions

$ atom --version

Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

-

**Comment by savetheclocktower** [comment]
I can’t quite work out the description of the problem. If it’s that a snippet suggestion doesn’t appear in the menu, then this is possibly an issue with the `autocomplete-snippets` package. If this is still happening for you, please open an issue there and describe the other packages you’re using that are relevant to the problem.
