### ISSUE TITLE
Undoing snippets leaks snippet tab stops at ends

### ISSUE THREAD

**Issue by Ingramz** [atom/snippets#261]
This is taken from #239

Consider these two snippets:
```
    prefix: "bug1"
    body: "$1expanded$0"
```

```
    prefix: "bug2"
    body: "$0expanded$1"
```

To reproduce the leakage, do:
Type `bug1` -> hit tab to expand snippet -> undo -> hit tab to expand snippet again -> hit tab again because it didn't work the first time: undo did not delete the tab stop at `$0` from the first time.

A more obvious version of this is the same, but with `bug2`:
Type `bug2` -> hit tab to expand snippet -> undo -> hit tab to expand snippet again: cursor jumps to the beginning of the prefix.

Pinging @nathansobo @savetheclocktower due to possible relevance from #260 wanting to improve on undo/redo. I thought this should be looked into while at it.

**Comment by 50Wliu** [comment]
Seems related to #248.

**Comment by nathansobo** [comment]
Put this on the triage board for discussion.

**Comment by Aerijo** [comment]
Is this still an issue? I wasn't able to reproduce either example. In the first, the cursor jumped to the start both times, and in the second it stayed at the end.

**Comment by Ingramz** [comment]
I am unable to reproduce this either anymore. Thanks for noticing, @Aerijo!

Closing the issue.

**Comment by Ingramz** [comment]
I shall also review whether we have a good regression test for this, so that it wouldn't happen again.
