### ISSUE TITLE
<unknown> is deprecated.

### ISSUE THREAD

**Issue by Wzicheng** [atom/snippets#279]
You have the core package "snippets" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
```
<unknown> (<embedded>:13661:20)
Generator.next (null:null:null)
step (<embedded>:13648:279)
<unknown> (null:null:null)
process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by 50Wliu** [comment]
Please follow the instructions listed in your issue.
