### ISSUE TITLE
Snippets with variable

### ISSUE THREAD

**Issue by ar-lli** [atom/snippets#294]
I'm new at snippets and I was wondering if there is a way to include some structural variable into the snippets. For example:
I'm writing in latex and for almost all the time in math environment. So I often need to include matrix in my file. So the question is:
Is it possible to create a snippet that takes as parameter the matrix dimensions and "builds" the structure with & and \\ characters, so as to pass through the space with tab?

**Comment by digitalTrilunaire** [comment]
Hello, I think you are confusing scripting and snippets. A snippet is a piece of code with a fixed length and you can customise the value of some part of this code, but there is no process to build a piece of code from given values, the piece of code of your snippet is fixed. What you might want to look can be a snippet with the dimensions of the matrix that you most commonly use, or simple program with 3 arguments (height, width and an arrray of values) that output a latex matrix.

**Comment by savetheclocktower** [comment]
You can create a command that does what you want, then use the programmatic interface to this package to insert arbitrary text as a snippet.

Here's an example of how that works:

```js
atom.commands.add('atom-text-editor', {
  'custom:some-command': () => {
    let snippet = atom.packages.activePackages.snippets.mainModule;

    // Build a snippet using whatever logic you want, perhaps grabbing the
    // selected text as a variable.
    let someRawSnippetString = ``;

    // Create a snippet on the fly and invoke it in the editor.    
    snippet.insert(someRawSnippetString);
  }
});
```
