### ISSUE TITLE
Regex Support

### ISSUE THREAD

**Issue by Grimeh** [atom/snippets#40]
Feature Request:
Support for regular expressions, to enable stuff like method name camel-casing, particularly useful for getters and setters.

**Comment by postal2600** [comment]
Another feature would be to implement smart HTML snippets as in ST: if you type `div#mama` and press `TAB` it will auto-complete to `<div id="mama"></div>`. I would love this in Atom like my next breath. 

If this is implemented it could replace the current snippet list from the html-language.

**Comment by coopermaruyama** [comment]
+1 for this! This is a basic feature in Sublime/Textmate that I really miss.

**Comment by afanasy** [comment]
+1

**Comment by andersonbarutti** [comment]
+1

**Comment by sdwrage** [comment]
+1

**Comment by ddelrio1986** [comment]
+1

**Comment by killswitch** [comment]
:+1:

**Comment by josa42** [comment]
:+1:

**Comment by rob2022** [comment]
:+1:

**Comment by evanwarner** [comment]
+1

**Comment by rrd108** [comment]
+1

**Comment by zyklus** [comment]
+1

**Comment by prog666** [comment]
+1

**Comment by prog666** [comment]
that's the only thing preventing me from using atom every day

**Comment by anlek** [comment]
wow, soul crushed when I learned this.
+:100:

**Comment by chvonrohr** [comment]
:+1:

**Comment by Stephn-R** [comment]
:+1: pinging for updates

**Comment by wadehammes** [comment]
+1

**Comment by prog666** [comment]
-1, learned vim already

**Comment by PierBover** [comment]
+1

**Comment by sdwrage** [comment]
This is not an option for most that don't use vim mode.

**Comment by jpmurray** [comment]
Is there any workaround for this? I'd love to be able to modify the case of some variables in a snippet.

**Comment by sdwrage** [comment]
Not currently that I know of other than just using vim mode. Hopefully
someone will contribute to atom and add the support.

**Comment by sjmas** [comment]
👍

**Comment by V0idExp** [comment]
:+1:

**Comment by joshmanders** [comment]
Thumbs up's aren't needed, Github now has reactions on posts. If you agree with something please use those. We don't need spam in our inboxes with 👍 anymore.

**Comment by Grimeh** [comment]
So would the sublime-style syntax for this be fine?

Instead of the two tab stop forms we have now:
 - `${1}`/`$1`
 - `${1:default}`

We would have an additional form:
 - `${1/regex/format/options}`

In people's opinions, would that be acceptable? 

One issue I see with this is that there's no way currently to use the regex tab stop without a second tab stop of the same field number in one of the first two forms. Unless the regex is evaluated and formatting applied in some sort of finalisation stage. Please correct me if I'm wrong.

**Comment by treetrum** [comment]
Any progress on this? I assume not. It's the only feature I miss from Sublime.

**Comment by savetheclocktower** [comment]
I’m taking a stab at this.

As a former TextMate 2 user, my initial impulse was to try to port over the entire “format string” syntax [as described here](http://manual.macromates.com/en/regular_expressions#replacement_string_syntax_format_strings). There are two main features:

## Case Foldings

Allows you to manipulate casing in capture groups. So given this contrived snippet…

```
<$1></${1/(.)(.*)/\u$1$2/}>
```

…typing `something` would produce…

```
<something></Something>
```

## Conditional Insertions

Allows you to include arbitrary content in a replacement based on whether a capture group was matched. So given this contrived snippet…

```
function $1 () {
  return${1/^(is)?(.*)$/(?1: true)/};
}
```

…typing `isActive` would produce…

```
function isActive () {
  return true;
}
```

…whereas typing `setActive` would produce…

```
function setActive () {
  return;
}
```

# Plan

I’m going to implement case foldings — they’re quite useful — but I’m going to punt on conditional insertions for now. With a few exceptions, I’ve only ever seen them used in the snippets that are bundled with TextMate.

Am I wrong about this? You all are likely to be snippet power users, so I’m curious to know if my assumptions are correct.

I don’t have much experience with Sublime Text, but if any of the features of [their format strings](http://www.boost.org/doc/libs/1_56_0/libs/regex/doc/html/boost_regex/format/boost_format_syntax.html) would be incredibly useful, let me know.

**Comment by savetheclocktower** [comment]
What I described above has been implemented in PR #260. Try it out if you like and let me know what you think.

**Comment by nathansobo** [comment]
Thanks to @savetheclocktower, transformations with case modifier flags are now implemented and will be available in Atom 1.25. I guess there's a couple more features to add before we officially close this.

**Comment by 50Wliu** [comment]
Since regex support was the main request of this issue and it has been mostly implemented in #260, I'm going to close this issue in favor more targeted ones.  If #260 did not implement what you were asking for, please open a new issue!

**Comment by jpduckwo** [comment]
Using Atom 1.28  if I try to use \u in the body of a snippet I get 
![image](https://user-images.githubusercontent.com/13150911/42977954-81d2233c-8c0d-11e8-9540-eb00d1708b92.png)
Any idea?

**Comment by Aerijo** [comment]
@jpduckwo Snippet definitions are strings, so all backslashes must be escaped. E.g., `\\n` for newline, `\\\\` for literal backslash.

**Comment by jpduckwo** [comment]
Thanks @Aerijo, I'm trying to do a transformation as described by @savetheclocktower [see PR](https://github.com/atom/snippets/pull/260)
e.g.
```<$1></${1/(.)(.*)/\u$1$2/}>``` 
However I can't seem to get a case transformation working with \U \u etc... has anyone got a working example of that? I've tried escaping the backslash.

**Comment by Aerijo** [comment]
What are you expecting? This works fine for me (I've translated some of what you had before too)
```
'*':
  'foo':
    'prefix': 'bar'
    'body': '<$1></${1/(.+)/\\u$1/}>'
```
Try it in any file. As per the definition of `\u`, it will set the first letter in the string to be a capital. The two capture groups were not required for this.

**Comment by Zakgeki** [comment]
Is there support for regex in the prefix of a snippet? I've seen in a snippet plguin for vim where you could in put `3/` and it would transform it to `\frac{3}{ }`. The snippet was setup something like this.

```

**Comment by savetheclocktower** [comment]
I’m not the final word on the issue, but I’d be surprised if that got implemented.

The good news is that it's pretty easy to write something in your init script (or as its own package) that would do what you're describing. I've got a similar command that'll let me type `foo`, hit <kbd>Shift + Return</kbd>, and have `foo` replaced with `function foo () {` (et cetera) when I'm in JavaScript files.

I've defined this in my init script:

```js
function getSnippetsModule () {
  let p = atom.packages.activePackages;
  if (p.snippets) { return p.snippets.mainModule; }
  return null;
}
```

If the snippets package is not active, that'll return null, but otherwise it'll return an object with an `insert` method. So you could do something like this:

```js
function expandFrac (e) {
  let editor = atom.workspace.getActiveTextEditor();
  let [cursor] = editor.getCursors(); // (grab the first cursor)
  let currentWord = cursor.getCurrentWordBufferRange();
  let match = currentWord.match(/(\d+)\/$/);
  let m = getSnippetsModule();
  if ( !m || !match ) {
    e.abortKeyBinding();
    return;
  }
  let snippet = `\\\\frac(${match[1]}{$1}$0)`;
  m.insert(snippet, editor, cursor);
}

atom.commands.add('atom-text-editor', {
  'custom:expand-frac': expandFrac
});
```

The `insert` method is insanely useful here because it groks snippet syntax. (I even prefer it to `editor.insertText` in most cases because you can also easily specify where the cursor should be afterward using `$0`.)

Then you can bind `custom:expand-frac` to some keystroke in your keymap file, perhaps even scoping it only to LaTeX files:

```
'atom-text-editor[data-grammar=\'text tex\'], atom-text-editor[data-grammar=\'text tex latex\']':
  'shift-enter': 'custom:expand-frac'
```

…or whatever keystroke you'd want instead of shift-enter.

If you have a _bunch_ of snippets like these, you could define an array of regexes with corresponding handlers for how to convert the input, then change `expandFrac` to work more generically.
