### ISSUE TITLE
Long snippets, spanning several lines

### ISSUE THREAD

**Issue by moltar** [atom/snippets#42]
Is there a good solution to this? It seems like the only option is to litter the snippet with `\n`s, which makes it very ugly and difficult to maintain. Sublime had neat XML files that did not get in the way of formatting. Or am I missing something?

Thanks!

**Comment by ANKerD** [comment]
I am trying to build a package that holds snippets that are 50 lines long, each snippet. I didn't find how to insert an external file to my snippets. Any help?

**Comment by savetheclocktower** [comment]
There’s no support for that, sorry. Is there a reason they need to come from an external file?

**Comment by ANKerD** [comment]
It's just a matter of readability. The package in question is for my data structures codes and I don't like the idea of putting everything in snippets.cson since a file with 500+ lines is hard to understand and maintain.

**Comment by savetheclocktower** [comment]
Gotcha. Your best bet would be some sort of build task that generates the CSON file from a source of your choosing.
