### ISSUE TITLE
Support TM_* values

### ISSUE THREAD

**Issue by robballou** [atom/snippets#46]
In converting some sublime/textmate snippets, things like `TM_FILENAME` are not currently supported. In many cases these can be useful in snippets as placeholders/tab values or just as values within the expanded snippet. For example: https://github.com/robballou/drupal-sublimetext/blob/master/Snippets/hook.sublime-snippet (this snippet will create a function with the filename preprended to the front of the function name).

I noticed in the APM conversion that they are normally replaced with `$1` but this won't necessarily be a correct replacement in many cases.

Thanks!

**Comment by haasDev** [comment]
has anything happened with this?  Would be really awesome.

**Comment by pmrotule** [comment]
Any updates? Really looking forward to this

**Comment by savetheclocktower** [comment]
Several issues are open asking for variable support; I’m anointing #41 as the canonical feature request and closing the others as dupes.
