### ISSUE TITLE
snippets:expand on tab (default) inside PHP variable triggered

### ISSUE THREAD

**Issue by IwanLuijksQuestMedia** [atom/snippets#59]
When I define a variable in PHP, and my cursor is within the variable '$address' (between the double 's'), or right after the variable '$address' and I hit [tab] the 'snippets:expand' command is triggered:
![schermafbeelding 2014-07-02 om 13 56 49](https://cloud.githubusercontent.com/assets/5575320/3455430/1bccd038-01e1-11e4-8a4f-df06a5647b9a.png)
![schermafbeelding 2014-07-02 om 13 57 02](https://cloud.githubusercontent.com/assets/5575320/3455451/5c1744d4-01e1-11e4-9a78-025f57eb70bf.png)

This is unexpected behavior, since I just wanted a tab being inserted.

From within the '$address'-variable it isn't very likely to occur (the double 's' expansion to ```<s></s>```), but hitting [tab] right after the variable definition is actually something I do a lot, and probably most do.

Maybe the **default** keybinding of [tab] to 'snippets:expand' could be changed to something else?

Mac OS X 10.8.5
Atom Version 0.106.0 (0.106.0)
Snippets package: 0.46.0

**Comment by maxbrunsfeld** [comment]
Ok, I believe this is fixed as of version 0.70.0. Please let us know if there are still bugs. Thanks!
