### ISSUE TITLE
Intermittent issues with opening snippets command dropdown menu

### ISSUE THREAD

**Issue by j-mes** [atom/snippets#66]
To start with, I'm using Windows 8.1 x64, and Atom Editor is currently at 0.120.0 (via chocolatey).

I love using the snippets functionality `alt+shift+s` but it doesn't always work, and it always opens the Selection menu on the toolbar first before typing something else to get rid of it to be able to type in the code I wanted to use from my own collection of snippets. Sometimes the snippets drop-down menu doesn't even come up at all, and the Selection menu comes up each time.

I'm wondering if this is an known issue or it's just a matter due to the keybindings being lost in translation from Mac to Windows?

**Comment by izuzak** [comment]
Closing this since the original issue was resolved and seems like it was actually about `autocomplete-snippets`, a community package which has since become a core package. I anyone notices this again -- please let us know.
