### ISSUE TITLE
Code allowed in snippets - intentional?

### ISSUE THREAD

**Issue by lee-dohm** [atom/snippets#85]
See: http://stackoverflow.com/questions/27115846/how-to-include-more-javascript-inside-atom-editor-by-github/27142128

cc @kevinsawicki

**Comment by maxbrunsfeld** [comment]
@kevinsawicki was this fixed via atom/atom#4971?

**Comment by kevinsawicki** [comment]
@maxbrunsfeld yup, thanks.
