### ISSUE TITLE
Not working at all now

### ISSUE THREAD

**Issue by jeffschwartz** [atom/snippets#96]
My snippet file:
```javascript
'.source.js':
    'Module':
        'prefix': 'mod'
        'body': """
(function($1){
    $2
}($3));
"""

'.source.js':
    'use strict':
        'prefix': 'us'
        'body': """
"use strict"$1
"""

'.source.js':
    'TODO':
        'prefix': 'td'
        'body': """
//TODO($1): $2
"""
```
The only changes on my end have been atom.io updates. I even disabled 2 add on pkgs that have seen a lot of updates lately (vim and jsonformat) assuming they might have been responsible for breaking snippets but nope.

**Comment by lee-dohm** [comment]
CSON is like JSON in that it is a compact way to write a JavaScript Object or hash. When you declare `'.source.js'` multiple times, you're **re**declaring it ... overwriting it. This should work better:

```coffee
'.source.js':
    'Module':
        'prefix': 'mod'
        'body': """
(function($1){
    $2
}($3));
"""
    'use strict':
        'prefix': 'us'
        'body': """
"use strict"$1
"""
    'TODO':
        'prefix': 'td'
        'body': """
//TODO($1): $2
"""
```

Also CoffeeScripts triple-quotes let you make it look nicer too because triple-quotes ignore whatever the common indentation is on all lines. Like so:

```coffee
'.source.js':
    'Module':
        'prefix': 'mod'
        'body': """
            (function($1){
                $2
            }($3));
            """
    'use strict':
        'prefix': 'us'
        'body': """
            "use strict"$1
            """
    'TODO':
        'prefix': 'td'
        'body': """
            //TODO($1): $2
            """
```

**Comment by jeffschwartz** [comment]
This is one of life's "ahhhhhhhhh!" moments. Yes, of course accompanied by the sound of head slapping lol.

I hope you don't mind but I'd like to make a suggestion that the commented out sample that appears in the snippets.CSON file shows something similar to yours above. I think it might prevent more of those head slapping "ahhhhhhhh" moments and less false flag issues like the one that I raised :)

Thank you, GitHub and all the atom.io supporters for your contributions to the OS developer community.

**Comment by lee-dohm** [comment]
Yeah, the latest CSON configuration files include the following text:

```coffee
# This file uses CoffeeScript Object Notation (CSON).
# If you are unfamiliar with CSON, you can read more about it here:
# https://github.com/bevry/cson#what-is-cson
```

But that doesn't help if you installed Atom before that was added ... and who looks at all the instructions in comments in config files anyway? :laughing:

I'll see what I can do to make the examples better.

**Comment by jeffschwartz** [comment]
:smile:
